apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-python
  namespace: test  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: my-python
          image: flask:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
          volumeMounts:
          - name: data-volume
            mountPath: /app/files
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: flask-pvc      
---
kind: Service
apiVersion: v1
metadata:
  name: my-python
  namespace: test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: python-app
